name: Build

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
      
      - name: Lint code
        run: yarn lint

      - name: Build app
        run: yarn build:app:dev
        
      - name: Check if build succeeded
        run: |
